# Generated by Django 5.2.8 on 2025-11-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/5e/1b/ba/join-us-for-a-delightful.jpg?w=900&h=500&s=1', max_length=500),
        ),
    ]
